version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: graylog_mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always
    networks:
      - aspnet8-network
    ports:
      - "27018:27017"  # Port 27018 trên host

  datanode:
    image: graylog/graylog-datanode:6.1
    container_name: graylog_datanode
    hostname: datanode
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: "Asia/Ho_Chi_Minh"
    volumes:
      - graylog_datanode:/var/lib/graylog-datanode
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - aspnet8-network

  graylog:
    image: graylog/graylog:6.1
    container_name: graylog_server
    depends_on:
      - mongodb
      - datanode
      - redis
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_HTTP_EXTERNAL_URI: "http://graylognet8.com:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
      GRAYLOG_TIMEZONE: "Asia/Ho_Chi_Minh"
    volumes:
      - graylog_data:/usr/share/graylog/data
    ports:
      - "9000:9000"
      - "5044:5044"
      - "5140:5140/udp"
      - "12201:12201/udp"
    restart: always
    networks:
      - aspnet8-network

  redis:
    image: redis:7.0
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - aspnet8-network

  webapi:
    image: webapi:${APP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: webapi_server
    restart: always
    ports:
      - "5000:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    networks:
      - aspnet8-network

volumes:
  mongodb_data:
    name: mongodb_data
  mongodb_config:
    name: mongodb_config
  graylog_datanode:
    name: graylog_datanode
  graylog_data:
    name: graylog_data
  redis_data:
    name: redis_data

networks:
  aspnet8-network:
    name: aspnet8-network
    driver: bridge

