<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Common\Shared.Common.csproj" />
  </ItemGroup>

</Project>
